server:
  port: 8881

spring:
  application:
    name: config-server
  cloud:
   config:
    label: master
    server:
#      native:
#        search-locations: classpath:/config/
     git:
       uri: https://github.com/Alex1119/springcloudDemo/
       search-paths: config-server/src/main/java/com/example/configserver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:900/eureka/